### ISSUE TITLE
No instructions before cooking.

### ISSUE THREAD

**Issue by Anduin2017** [LeeJim/HowToCookOnMiniprogram#2]
Instructions are also very important.

![c67716830d766a28b60dc6ff77632a5](https://user-images.githubusercontent.com/19531547/157814859-41e5f0e8-e82a-4bcb-a605-68fca8563496.png)

**Comment by LeeJim** [comment]
Yes, it's on its way

**Comment by Anduin2017** [comment]
Release confirmed.
