### ISSUE TITLE
数据有点儿老了，可以做个自动化更新

### ISSUE THREAD

**Issue by Anduin2017** [LeeJim/HowToCookOnMiniprogram#4]
我这几天修了好多原来菜谱里的bug。。。这里还能看到一些没更新

**Comment by os7blue** [comment]
我下载下来研究研究 看看能不能给他整个自动更新

**Comment by LeeJim** [comment]
感谢反馈，数据更新在后续的规划中

**Comment by ZeaKyX** [comment]
> 感谢反馈，数据更新在后续的规划中

@LeeJim 这个数据库子模块如果自动更新有用吗，我写了个 github action 供参考：
https://github.com/ZeaKyX/HowToCookOnMiniprogram/blob/main/.github/workflows/submodule.yml

**Comment by LeeJim** [comment]
已更新，发布 v1.1.2
